# Generated by Django 5.2.6 on 2025-09-28 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['email'], 'permissions': [('can_view_all_clients',
                                                             'Может просматривать всех получателей')],
                     'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['end_time'], 'permissions': [('can_view_all_mailings',
                                                                'Может просматривать все рассылки')],
                     'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['-attempt_time'], 'verbose_name': 'попытка рассылки',
                     'verbose_name_plural': 'попытки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_view_all_messages',
                                                               'Может просматривать все сообщения')],
                     'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='clients_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='mailings_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='mailings_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='messages_as_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.BooleanField(default=False, verbose_name='успешно ли'),
        ),
    ]
