# Generated by Django 5.2.6 on 2025-09-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='clients',
            new_name='client',
        ),
    ]
