# Generated by Django 5.2.6 on 2025-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_rename_clients_mailing_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
